# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

key1: a b c/,cba
key2:
    - subkey: val1
    - subkey: val2
key3: {subkey: val1, subkey2: val2}
key4: {subkey, subkey2}
key5:
   - a
   - b
key6: [val1, val2]
